services:
  db:
    image: postgres:15
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
    env_file:
      - ../.env


  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: auth_app
    depends_on:
      db :
        condition: service_healthy
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - ../.env
    command: ["/bin/sh", "-c", "goose -v -dir migrations postgres \"$${DB_DSN}\" up && /app/main"]


volumes:
  db_data:

